include:
  template: Dependency-Scanning.gitlab-ci.yml

image: python:alpine

before_script:
  - apk update && apk add gcc libffi-dev make musl-dev openssl-dev
  - pip install -r requirements.txt

pages:
  script:
    - python setup.py install
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master
